# Generated by Django 2.0.4 on 2018-04-07 20:37

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource', models.URLField()),
                ('kind', models.IntegerField(choices=[(1, 'upvote'), (2, 'downvote'), (3, 'close_pool')])),
                ('source_ip', models.GenericIPAddressField(null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('stored', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('editor', models.BooleanField(default=False)),
                ('professional_id', models.CharField(blank=True, max_length=55, null=True)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('stored', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('url', models.URLField(unique=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('editors_vote', models.IntegerField(choices=[(1, 'legit'), (2, 'fake'), (3, 'inconclusive')], null=True)),
                ('rewardable', models.BooleanField(default=True)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('same_as', models.ManyToManyField(related_name='_resource_same_as_+', to='core.Resource')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('stored', django.db.models.manager.Manager()),
            ],
        ),
    ]
